apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: synology-csi-node
spec:
  template:
    spec:
      tolerations:
        - key: "availability"
          operator: "Equal"
          value: "daytime"
          effect: "NoSchedule"
