apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homelab-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  dsm: "192.168.1.26"
  fsType: "btrfs"
  location: "/volume1"
  protocol: iSCSI
provisioner: csi.san.synology.com
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-box-smb
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  dsm: "192.168.1.26"
  fsType: "btrfs"
  location: "/volume1"
  protocol: iSCSI
provisioner: csi.san.synology.com
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hcloud-volumes
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
parameters:
  dsm: "192.168.1.26"
  fsType: "btrfs"
  location: "/volume1"
  protocol: iSCSI
provisioner: csi.san.synology.com
reclaimPolicy: Retain
allowVolumeExpansion: true
