apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
  data:
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: smtp-password
