apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: monitoring-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: garden-smtp-username
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: garden-smtp-password
