apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: monitoring-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: garden-smtp-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: garden-smtp-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
