apiVersion: k8s.homelab.timosur.com/v1
kind: AppDBClaim
metadata:
  name: vinyl-manager-db
  namespace: vinyl-manager
spec:
  appName: vinyl-manager
  databaseName: vinyl-manager
  roleName: vinyl-manager
  compositionRef:
    name: appdb-central-postgres
