apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        N8N_ENCRYPTION_KEY: "{{ .encryptionKey }}"
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: n8n-encryption-key
