apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config
  namespace: authentik
data:
  TZ: "Europe/Berlin"
  AUTHENTIK_REDIS__HOST: "authentik-redis"
  AUTHENTIK_POSTGRESQL__HOST: "central-postgres-rw.postgres.svc.cluster.local"
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__NAME: "authentik-main"
  AUTHENTIK_HOST: "https://auth.timosur.com"
  AUTHENTIK_HOST_BROWSER: "https://auth.timosur.com"
  AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: "10.0.0.0/8,192.168.0.0/16"
