apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-config
  namespace: authentik
data:
  TZ: "Europe/Berlin"
  AUTHENTIK_REDIS__HOST: "authentik-redis"
  AUTHENTIK_POSTGRESQL__HOST: "central-postgres-rw.postgres.svc.cluster.local"
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__NAME: "authentik-main"
