apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-smb
  resources:
    requests:
      storage: 5Gi
