apiVersion: v1
kind: Service
metadata:
  name: ferienhof-wiesengrund
  namespace: ferienhof-wiesengrund
spec:
  selector:
    app: ferienhof-wiesengrund
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
