apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - appdb.yaml
  - redis-pvc.yaml
  - redis.yaml
  - deployment.yaml

namespace: affine
