apiVersion: v1
kind: Service
metadata:
  name: bike-weather-agent
  namespace: bike-weather
spec:
  selector:
    app: bike-weather-agent
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
