apiVersion: k8s.homelab.timosur.com/v1
kind: AppDBClaim
metadata:
  name: bike-weather-db
  namespace: bike-weather
spec:
  appName: bike-weather
  databaseName: bike-weather
  roleName: bike-weather
  compositionRef:
    name: appdb-central-postgres
