apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appdb.yaml
  - ollama-dummy-secret.yaml
  - model-configs.yaml
  - remote-mcp-server.yaml
  - coding-agent.yaml
  - cilium-network-policy.yaml
