apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: devstral
  namespace: agents
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecret: kagent-ollama-dummy
  model: devstral:latest
  provider: Ollama
  ollama:
    host: http://ollama.agentgateway-system.svc.cluster.local:11434
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: ollama-mistral
  namespace: agents
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecret: kagent-ollama-dummy
  model: mistral:7b
  provider: Ollama
  ollama:
    host: http://ollama.agentgateway-system.svc.cluster.local:11434
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: ollama-nano
  namespace: agents
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecret: kagent-ollama-dummy
  model: nemotron-3-nano:4b
  provider: Ollama
  ollama:
    host: http://ollama.agentgateway-system.svc.cluster.local:11434
