apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
# Add Crossplane Providers, Configurations, or other resources here, e.g.:
# - provider-aws.yaml
# - provider-azure.yaml
