apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - provider-sql.yaml
  - function-go-templating.yaml
  - provider-config.yaml
  - xrd-appdb.yaml
  - composition-appdb.yaml
