apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: central-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  credentials:
    source: PostgreSQLConnectionString
    connectionStringSecretRef:
      namespace: postgres
      name: central-postgres-provider-connection
      key: connection-string
