apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: wol-auth-actual
  namespace: actual
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: actual
  extAuth:
    http:
      backendRefs:
        - name: authentik-server
          namespace: authentik
          port: 9000
      path: /outpost.goauthentik.io/auth/envoy
      headersToBackend:
        - cookie
        - authorization
