apiVersion: k8s.homelab.timosur.com/v1
kind: AppDBClaim
metadata:
  name: garden-db
  namespace: garden
spec:
  appName: garden
  databaseName: garden
  roleName: garden
  compositionRef:
    name: appdb-central-postgres
