apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-frontend
  namespace: garden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: garden-frontend
  template:
    metadata:
      labels:
        app: garden-frontend
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: garden-frontend
          image: ghcr.io/timosur/life-as-a-garden/frontend:1.0.2@sha256:0a6d19d2ac2d43a4b2ba24294c8d08e60d0816d86e4a9d7e92c27b1e37295fda
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
