apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - external-secret.yaml
  - cilium-network-policy.yaml
  - tetragon-policy.yaml
