apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bike-weather-preview-secrets
  namespace: bike-weather-preview
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: bike-weather-preview-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AUTHENTIK_API_TOKEN: "{{ .authentikApiToken }}"
        TURNSTILE_SECRET_KEY: "{{ .turnstileSecretKey }}"
        GOOGLE_MAPS_API_KEY: "{{ .googleMapsApiKey }}"
  data:
    - secretKey: authentikApiToken
      remoteRef:
        key: bike-weather-preview-authentik-api-token
    - secretKey: turnstileSecretKey
      remoteRef:
        key: bike-weather-preview-turnstile-secret-key
    - secretKey: googleMapsApiKey
      remoteRef:
        key: bike-weather-preview-google-maps-api-key
