apiVersion: k8s.homelab.timosur.com/v1
kind: AppDBClaim
metadata:
  name: atuin-db
  namespace: atuin
spec:
  appName: atuin
  databaseName: atuin
  roleName: atuin
  compositionRef:
    name: appdb-central-postgres
