apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-weather-auth-worker
  namespace: bike-weather-auth
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bike-weather-auth-worker
  template:
    metadata:
      labels:
        app: bike-weather-auth-worker
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-amd
      containers:
        - name: worker
          image: ghcr.io/goauthentik/server:2026.2.2
          command: ["ak", "worker"]
          envFrom:
            - configMapRef:
                name: bike-weather-auth-config
            - secretRef:
                name: bike-weather-auth-secrets
          env:
            - name: AUTHENTIK_POSTGRESQL__USER
              valueFrom:
                secretKeyRef:
                  name: bike-weather-auth-db-connection
                  key: username
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bike-weather-auth-db-connection
                  key: password
          volumeMounts:
            - name: media
              mountPath: /media
            - name: email-templates
              mountPath: /templates/email
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: bike-weather-auth-media
        - name: email-templates
          configMap:
            name: bike-weather-auth-email-templates
