apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: central-postgres-provider-connection
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: central-postgres-provider-connection
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        endpoint: "postgresql://{{ .username }}:{{ .password }}@central-postgres-rw.postgres.svc.cluster.local:5432/postgres?sslmode=disable"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: central-postgres-superuser-username
        metadataPolicy: None

    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: central-postgres-superuser-password
        metadataPolicy: None
