apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: central-postgres-superuser-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: central-postgres-superuser-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: central-postgres-superuser-username
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: central-postgres-superuser-password
        metadataPolicy: None
