apiVersion: v1
kind: ConfigMap
metadata:
  name: vuln-reporter-config
  namespace: trivy-system
data:
  SMTP_HOST: smtp.mail.me.com
  SMTP_PORT: "587"
  SMTP_USERNAME: mail@timosur.com
  EMAIL_FROM: mail@timosur.com
  EMAIL_TO: homelab@timosur.com
