apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wol-proxy-ssh-key
  namespace: wol-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: wol-proxy-ssh-key
    creationPolicy: Owner
  data:
    - secretKey: ssh-key
      remoteRef:
        key: wol-proxy-ssh-key
