apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: v2.2.0
      helm:
        valuesObject: {}
    - repoURL: https://github.com/timosur/homelab.git
      targetRevision: HEAD
      path: apps/crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
