apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm/kagent-crds
    chart: kagent-crds
    targetRevision: 0.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
