apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeopencode
  namespace: argocd
spec:
  project: default
  sources:
    - helm:
        valuesObject:
          server:
            enabled: true
      chart: kubeopencode
      repoURL: oci://quay.io/kubeopencode/helm-charts
      targetRevision: 0.0.21
    - repoURL: https://github.com/timosur/homelab.git
      targetRevision: HEAD
      path: apps/kubeopencode
  destination:
    namespace: kubeopencode-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
