apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sos-page-data
  namespace: sos
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: sos-page-data
    creationPolicy: Owner
  data:
    - secretKey: data.json
      remoteRef:
        key: sos-page-data
