apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentgateway-openai-secret
  namespace: agentgateway-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: agentgateway-openai-secret
    creationPolicy: Owner
  data:
    - secretKey: Authorization
      remoteRef:
        key: agentgateway-openai-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentgateway-anthropic-secret
  namespace: agentgateway-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: agentgateway-anthropic-secret
    creationPolicy: Owner
  data:
    - secretKey: Authorization
      remoteRef:
        key: agentgateway-anthropic-api-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
