apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: inference-api-key-authentication
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agentgateway-proxy
      sectionName: https
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: agentgateway-proxy
      sectionName: mcp-https
  traffic:
    apiKeyAuthentication:
      mode: Strict
      secretRef:
        name: agentgateway-inference-api-key
      location:
        header:
          name: Authorization
          prefix: Bearer
