apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin-ui-service.yaml
  - agentgateway-anthropic-secret.yaml
  - agentgateway-inference-api-key.yaml
  - agentgateway-mcp-api-keys.yaml
  - agentgateway-openai-secret.yaml
  - agentgateway-parameters.yaml
  - agentgateway-proxy.yaml
  - anthropic-ai-backend.yaml
  - context7-mcp-backend.yaml
  - context7-mcp-route.yaml
  - inference-certificate.yaml
  - inference-policy.yaml
  - kagi-mcp-backend.yaml
  - kagi-mcp-route.yaml
  - llm-inference-route.yaml
  - network-policy.yaml
  - obscura-deployment.yaml
  - obscura-mcp-backend.yaml
  - obscura-mcp-route.yaml
  - obscura-network-policy.yaml
  - obscura-service.yaml
  - ollama-ai-backend.yaml
  - ollama-backend.yaml
  - openai-ai-backend.yaml
