apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: ollama
  namespace: agentgateway-system
spec:
  ai:
    provider:
      openai:
        model: devstral:latest
      host: ollama.agentgateway-system.svc.cluster.local
      port: 11434
