apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smb-creds
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: smb-creds
    creationPolicy: Owner
    template:
      data:
        username: "{{ .synology_username }}"
        password: "{{ .synology_password }}"
  data:
    - secretKey: synology_username
      remoteRef:
        key: synology-csi-username
    - secretKey: synology_password
      remoteRef:
        key: synology-csi-password
