apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-store
    kind: ClusterSecretStore
  target:
    name: open-webui-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        google-pse-api-key: "{{ .googlePseApiKey }}"
        google-pse-engine-id: "{{ .googlePseEngineId }}"
        openai-api-key: "{{ .openaiApiKey }}"
        webui-secret-key: "{{ .webuiSecretKey }}"
        open-terminal-api-key: "{{ .openTerminalApiKey }}"
        terminal-server-connections: '[{"id":"open-terminal","name":"Open Terminal","enabled":true,"url":"http://open-terminal-service.open-webui.svc.cluster.local:8000","path":"/openapi.json","key":"{{ .openTerminalApiKey }}","auth_type":"bearer"}]'
  data:
    - secretKey: googlePseApiKey
      remoteRef:
        key: open-webui-google-pse-api-key
    - secretKey: googlePseEngineId
      remoteRef:
        key: open-webui-google-pse-engine-id
    - secretKey: openaiApiKey
      remoteRef:
        key: open-webui-openai-api-key
    - secretKey: webuiSecretKey
      remoteRef:
        key: open-webui-secret-key
    - secretKey: openTerminalApiKey
      remoteRef:
        key: open-webui-open-terminal-api-key
