apiVersion: v1
kind: Namespace
metadata:
  name: open-webui
  labels:
    exposure: internet
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
