apiVersion: v1
kind: Service
metadata:
  name: open-terminal-service
  namespace: open-webui
spec:
  type: ClusterIP
  selector:
    app: open-terminal
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
