apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-terminal
  name: open-terminal-pvc
  namespace: open-webui
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
